// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TestePraticoTPC.Models;

public partial class TestePraticoTPCContext : DbContext
{
    public TestePraticoTPCContext()
    {
    }

    public TestePraticoTPCContext(DbContextOptions<TestePraticoTPCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tarefas> Tarefas { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=RAFA;Initial Catalog=TestePraticoTPC;Persist Security Info=True;User ID=sa;Password=9173rafa;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tarefas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tarefas__3214EC0718EFDA2C");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Tarefas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Tarefas_Usuarios");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC07EC19FCAE");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}