// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestePraticoTPC.Models;

public partial class Tarefas
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Titulo { get; set; }

    [StringLength(500)]
    public string Descricao { get; set; }

    public int Status { get; set; }

    public int UsuarioId { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("Tarefas")]
    public virtual Usuarios Usuario { get; set; }
}