// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TestePraticoTPC.Models;

[Index("Email", Name = "UQ__Usuarios__A9D10534EB602D7B", IsUnique = true)]
public partial class Usuarios
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Nome { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string Senha { get; set; }

    [InverseProperty("Usuario")]
    public virtual ICollection<Tarefas> Tarefas { get; set; } = new List<Tarefas>();
}